/* Generated By:JavaCC: Do not edit this line. ATCollectionParserConstants.java */
package com.gpl.rpg.AndorsTrail.scripting.collectionparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ATCollectionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DQUO = 1;
  /** RegularExpression Id. */
  int DOT = 2;
  /** RegularExpression Id. */
  int LBRAC = 3;
  /** RegularExpression Id. */
  int MAP = 4;
  /** RegularExpression Id. */
  int ON_ENTER = 5;
  /** RegularExpression Id. */
  int ON_LEAVE = 6;
  /** RegularExpression Id. */
  int ATTACK = 7;
  /** RegularExpression Id. */
  int ON_HIT = 8;
  /** RegularExpression Id. */
  int ON_MISS = 9;
  /** RegularExpression Id. */
  int SCRIPT_ID = 10;
  /** RegularExpression Id. */
  int WHITESPACE = 11;
  /** RegularExpression Id. */
  int RBRAC = 12;
  /** RegularExpression Id. */
  int CODE = 13;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int SCRIPT_CODE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\\"\"",
    "\".\"",
    "\"[\"",
    "\"map\"",
    "\"onEnter\"",
    "\"onLeave\"",
    "\"attack\"",
    "\"onHit\"",
    "\"onMiss\"",
    "<SCRIPT_ID>",
    "<WHITESPACE>",
    "\"]\"",
    "<CODE>",
  };

}
