/* Generated By:JavaCC: Do not edit this line. ATCollectionParserConstants.java */
package com.gpl.rpg.AndorsTrail.scripting.collectionparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ATCollectionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DQUO = 5;
  /** RegularExpression Id. */
  int DOT = 6;
  /** RegularExpression Id. */
  int LBRAC = 7;
  /** RegularExpression Id. */
  int MAP = 8;
  /** RegularExpression Id. */
  int ON_ENTER = 9;
  /** RegularExpression Id. */
  int ON_LEAVE = 10;
  /** RegularExpression Id. */
  int ATTACK = 11;
  /** RegularExpression Id. */
  int ON_HIT = 12;
  /** RegularExpression Id. */
  int ON_MISS = 13;
  /** RegularExpression Id. */
  int SCRIPT_ID = 14;
  /** RegularExpression Id. */
  int RBRAC = 15;
  /** RegularExpression Id. */
  int CODE = 16;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int SCRIPT_CODE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\\"\"",
    "\".\"",
    "\"[\"",
    "\"map\"",
    "\"onEnter\"",
    "\"onLeave\"",
    "\"attack\"",
    "\"onHit\"",
    "\"onMiss\"",
    "<SCRIPT_ID>",
    "\"]\"",
    "<CODE>",
  };

}
