/* Generated By:JavaCC: Do not edit this line. ATScriptParserConstants.java */
package com.gpl.rpg.AndorsTrail.scripting.interpreter;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ATScriptParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DOT = 5;
  /** RegularExpression Id. */
  int LPAR = 6;
  /** RegularExpression Id. */
  int RPAR = 7;
  /** RegularExpression Id. */
  int LBRAC = 8;
  /** RegularExpression Id. */
  int RBRAC = 9;
  /** RegularExpression Id. */
  int SCOL = 10;
  /** RegularExpression Id. */
  int COMA = 11;
  /** RegularExpression Id. */
  int IF = 12;
  /** RegularExpression Id. */
  int ELSE = 13;
  /** RegularExpression Id. */
  int WHILE = 14;
  /** RegularExpression Id. */
  int RETURN = 15;
  /** RegularExpression Id. */
  int TRUE = 16;
  /** RegularExpression Id. */
  int FALSE = 17;
  /** RegularExpression Id. */
  int EXCLAM = 18;
  /** RegularExpression Id. */
  int GOE = 19;
  /** RegularExpression Id. */
  int LOE = 20;
  /** RegularExpression Id. */
  int GT = 21;
  /** RegularExpression Id. */
  int LT = 22;
  /** RegularExpression Id. */
  int EQ = 23;
  /** RegularExpression Id. */
  int PLUS = 24;
  /** RegularExpression Id. */
  int MINUS = 25;
  /** RegularExpression Id. */
  int MULTIPLY = 26;
  /** RegularExpression Id. */
  int DIVIDE = 27;
  /** RegularExpression Id. */
  int CONCAT = 28;
  /** RegularExpression Id. */
  int AND = 29;
  /** RegularExpression Id. */
  int OR = 30;
  /** RegularExpression Id. */
  int EQUALS = 31;
  /** RegularExpression Id. */
  int DQUO = 32;
  /** RegularExpression Id. */
  int NUMBER = 33;
  /** RegularExpression Id. */
  int MAP = 34;
  /** RegularExpression Id. */
  int WORLD = 35;
  /** RegularExpression Id. */
  int ATTACK = 36;
  /** RegularExpression Id. */
  int PLAYER = 37;
  /** RegularExpression Id. */
  int ACTOR = 38;
  /** RegularExpression Id. */
  int OUTDOOR = 39;
  /** RegularExpression Id. */
  int MIN = 40;
  /** RegularExpression Id. */
  int MAX = 41;
  /** RegularExpression Id. */
  int CURRENT = 42;
  /** RegularExpression Id. */
  int SOURCE = 43;
  /** RegularExpression Id. */
  int TARGET = 44;
  /** RegularExpression Id. */
  int DAMAGE = 45;
  /** RegularExpression Id. */
  int ADDCONDITION = 46;
  /** RegularExpression Id. */
  int CLEARCONDITION = 47;
  /** RegularExpression Id. */
  int HP = 48;
  /** RegularExpression Id. */
  int AP = 49;
  /** RegularExpression Id. */
  int AC = 50;
  /** RegularExpression Id. */
  int AD = 51;
  /** RegularExpression Id. */
  int BC = 52;
  /** RegularExpression Id. */
  int DR = 53;
  /** RegularExpression Id. */
  int CC = 54;
  /** RegularExpression Id. */
  int CM = 55;
  /** RegularExpression Id. */
  int BOOL = 56;
  /** RegularExpression Id. */
  int NUM = 57;
  /** RegularExpression Id. */
  int STRING = 58;
  /** RegularExpression Id. */
  int IDENTIFIER = 59;
  /** RegularExpression Id. */
  int ESCAPED_DQUO = 60;
  /** RegularExpression Id. */
  int DQUOBIS = 61;
  /** RegularExpression Id. */
  int LITERAL_VALUE = 62;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int LITERAL = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"return\"",
    "\"true\"",
    "\"false\"",
    "\"!\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"&&\"",
    "\"||\"",
    "\"=\"",
    "\"\\\"\"",
    "<NUMBER>",
    "\"map\"",
    "\"world\"",
    "\"attack\"",
    "\"player\"",
    "\"actor\"",
    "\"outdoor\"",
    "\"min\"",
    "\"max\"",
    "\"current\"",
    "\"source\"",
    "\"target\"",
    "\"damage\"",
    "\"addActorCondition\"",
    "\"clearActorCondition\"",
    "\"hp\"",
    "\"ap\"",
    "\"ac\"",
    "\"ad\"",
    "\"bc\"",
    "\"dr\"",
    "\"cc\"",
    "\"cm\"",
    "\"bool\"",
    "\"num\"",
    "\"string\"",
    "<IDENTIFIER>",
    "\"\\\\\\\"\"",
    "\"\\\"\"",
    "<LITERAL_VALUE>",
  };

}
