/* Generated By:JavaCC: Do not edit this line. ATScriptParser.java */
package com.gpl.rpg.AndorsTrail.scripting.interpreter;

import java.io.BufferedReader;
import java.io.StringReader;

public class ATScriptParser implements ATScriptParserConstants {

        public static ATSNode parseScript(String script, ATSLocalVarsHelper localVarRefHelp) throws ParseException {
                StringReader reader = new StringReader(script);
                BufferedReader scriptReader = new BufferedReader(reader);
                ATScriptParser parser = new ATScriptParser(scriptReader);
                try {
                        return parser.parseScope(localVarRefHelp);
                } catch (Exception e) {
                        e.printStackTrace();
                } catch (Error e) {
                        e.printStackTrace();
                }
                return null;
        }

  final public ATSExpression parseScope(ATSLocalVarsHelper localVars) throws ParseException {
        ATSExpression scriptRoot;
        localVars.pushScope();
    scriptRoot = parseScript(localVars);
                localVars.popScope();
                {if (true) return scriptRoot;}
    throw new Error("Missing return statement in function");
  }

  final public ATSExpression parseScript(ATSLocalVarsHelper localVars) throws ParseException {
        ATSExpression scriptRoot, next;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF:
    case WHILE:
    case RETURN:
    case MAP:
    case WORLD:
    case ATTACK:
    case PLAYER:
    case ACTOR:
    case ITEM:
    case BOOL:
    case NUM:
    case STRING:
    case OBJECT:
    case IDENTIFIER:
      scriptRoot = construct(localVars);
      next = parseScript(localVars);
                scriptRoot.next = next;
                {if (true) return scriptRoot;}
      break;
    case 0:
      jj_consume_token(0);
                {if (true) return null;}
      break;
    case RBRAC:
      jj_consume_token(RBRAC);
                {if (true) return null;}
      break;
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ATSExpression construct(ATSLocalVarsHelper localVars) throws ParseException {
        ATSExpression construct;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MAP:
    case WORLD:
    case ATTACK:
    case PLAYER:
    case ACTOR:
    case ITEM:
    case BOOL:
    case NUM:
    case STRING:
    case OBJECT:
    case IDENTIFIER:
      construct = associationOrMethodCall(localVars);
                {if (true) return construct;}
      break;
    case IF:
      construct = ifElseConstruct(localVars);
                {if (true) return construct;}
      break;
    case WHILE:
      construct = whileConstruct(localVars);
                {if (true) return construct;}
      break;
    case RETURN:
      construct = returnConstruct(localVars);
                {if (true) return construct;}
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ATSExpression associationOrMethodCall(ATSLocalVarsHelper localVars) throws ParseException {
        ATSValueReference assignee;
        ATSValueReference value = null;
    assignee = reference(localVars);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQUALS:
      jj_consume_token(EQUALS);
      value = value(localVars);
      break;
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    jj_consume_token(SCOL);
                if (value != null) {
                        {if (true) return new ATSAssociation(assignee, value);}
                } else {
                        //Method call...
                        {if (true) return assignee;}
                }
    throw new Error("Missing return statement in function");
  }

  final public ATSValueReference reference(ATSLocalVarsHelper localVars) throws ParseException {
        ATSValueReference assignee;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BOOL:
    case NUM:
    case STRING:
    case OBJECT:
      assignee = localVarDeclaration(localVars);
                {if (true) return assignee;}
      break;
    case MAP:
    case WORLD:
    case ATTACK:
    case PLAYER:
    case ACTOR:
    case ITEM:
    case IDENTIFIER:
      assignee = contextVarReference(localVars);
                {if (true) return assignee;}
      break;
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ATSValueReference localVarDeclaration(ATSLocalVarsHelper localVars) throws ParseException {
        Token id;
        int index;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BOOL:
      jj_consume_token(BOOL);
      id = jj_consume_token(IDENTIFIER);
                if (localVars.getLocalVar(id.image)!= null) {
                        {if (true) throw new ParseException("ATScript : Duplicate variable "+id.image+" at line "+id.beginLine+" column "+id.beginColumn);}
                }
                {if (true) return localVars.newBoolVariable(id.image);}
      break;
    case NUM:
      jj_consume_token(NUM);
      id = jj_consume_token(IDENTIFIER);
                if (localVars.getLocalVar(id.image)!= null) {
                        {if (true) throw new ParseException("ATScript : Duplicate variable "+id.image+" at line "+id.beginLine+" column "+id.beginColumn);}
                }
                {if (true) return localVars.newNumVariable(id.image);}
      break;
    case STRING:
      jj_consume_token(STRING);
      id = jj_consume_token(IDENTIFIER);
                if (localVars.getLocalVar(id.image)!=null) {
                        {if (true) throw new ParseException("ATScript : Duplicate variable "+id.image+" at line "+id.beginLine+" column "+id.beginColumn);}
                }
                {if (true) return localVars.newStringVariable(id.image);}
      break;
    case OBJECT:
      jj_consume_token(OBJECT);
      id = jj_consume_token(IDENTIFIER);
                if (localVars.getLocalVar(id.image)!=null) {
                        {if (true) throw new ParseException("ATScript : Duplicate variable "+id.image+" at line "+id.beginLine+" column "+id.beginColumn);}
                }
                {if (true) return localVars.newObjectVariable(id.image);}
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ATSValueReference contextVarReference(ATSLocalVarsHelper localVars) throws ParseException {
        ATSValueReference reference = null;
        Token id;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MAP:
      jj_consume_token(MAP);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DOT:
        jj_consume_token(DOT);
        reference = mapReference(localVars, new ATSContextObjectReference(ATSContextObjectReference.ContextObject.map));
        break;
      default:
        jj_la1[5] = jj_gen;
        ;
      }
                if (reference != null) {if (true) return reference;}
                {if (true) return new ATSContextObjectReference(ATSContextObjectReference.ContextObject.map);}
      break;
    case ATTACK:
      jj_consume_token(ATTACK);
      jj_consume_token(DOT);
      reference = attackReference(localVars);
                {if (true) return reference;}
      break;
    case PLAYER:
      jj_consume_token(PLAYER);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DOT:
        jj_consume_token(DOT);
        reference = playerReference(localVars);
        break;
      default:
        jj_la1[6] = jj_gen;
        ;
      }
                if (reference != null) {if (true) return reference;}
                {if (true) return new ATSContextObjectReference(ATSContextObjectReference.ContextObject.player);}
      break;
    case ACTOR:
      jj_consume_token(ACTOR);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DOT:
        jj_consume_token(DOT);
        reference = actorReference(localVars, new ATSContextObjectReference(ATSContextObjectReference.ContextObject.actor));
        break;
      default:
        jj_la1[7] = jj_gen;
        ;
      }
                if (reference != null) {if (true) return reference;}
                {if (true) return new ATSContextObjectReference(ATSContextObjectReference.ContextObject.actor);}
      break;
    case WORLD:
      jj_consume_token(WORLD);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DOT:
        jj_consume_token(DOT);
        reference = worldReference(localVars);
        break;
      default:
        jj_la1[8] = jj_gen;
        ;
      }
                if (reference != null) {if (true) return reference;}
                {if (true) return new ATSContextObjectReference(ATSContextObjectReference.ContextObject.world);}
      break;
    case ITEM:
      jj_consume_token(ITEM);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DOT:
        jj_consume_token(DOT);
        reference = itemReference(localVars, new ATSContextObjectReference(ATSContextObjectReference.ContextObject.item));
        break;
      default:
        jj_la1[9] = jj_gen;
        ;
      }
                if (reference != null) {if (true) return reference;}
                {if (true) return new ATSContextObjectReference(ATSContextObjectReference.ContextObject.item);}
      break;
    case IDENTIFIER:
      id = jj_consume_token(IDENTIFIER);
                ATSLocalVarReference var = localVars.getLocalVar(id.image);
                if (var == null) {
                        {if (true) throw new ParseException("Undeclared variable "+id.image+" at line"+id.beginLine+" column "+id.beginColumn);}
                }
                {if (true) return var;}
      break;
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ATSExpression whileConstruct(ATSLocalVarsHelper localVars) throws ParseException {
        ATSExpression block;
        ATSValueReference condition;
    jj_consume_token(WHILE);
    jj_consume_token(LPAR);
    condition = value(localVars);
    jj_consume_token(RPAR);
    jj_consume_token(LBRAC);
    block = parseScope(localVars);
                {if (true) return new ATSWhileLoop(condition, block);}
    throw new Error("Missing return statement in function");
  }

  final public ATSExpression ifElseConstruct(ATSLocalVarsHelper localVars) throws ParseException {
        ATSExpression ifBlock, elseBlock=null;
        ATSValueReference ifCondition;
    jj_consume_token(IF);
    jj_consume_token(LPAR);
    ifCondition = value(localVars);
    jj_consume_token(RPAR);
    jj_consume_token(LBRAC);
    ifBlock = parseScope(localVars);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ELSE:
      jj_consume_token(ELSE);
      elseBlock = elseBlock(localVars);
      break;
    default:
      jj_la1[11] = jj_gen;
      ;
    }
                {if (true) return new ATSFlowControl(ifCondition,ifBlock,elseBlock);}
    throw new Error("Missing return statement in function");
  }

  final public ATSExpression elseBlock(ATSLocalVarsHelper localVars) throws ParseException {
        ATSExpression block;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LBRAC:
      jj_consume_token(LBRAC);
      block = parseScope(localVars);
                {if (true) return block;}
      break;
    case IF:
      block = ifElseConstruct(localVars);
                {if (true) return block;}
      break;
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ATSExpression returnConstruct(ATSLocalVarsHelper localVars) throws ParseException {
        ATSValueReference value;
    jj_consume_token(RETURN);
    value = value(localVars);
                {if (true) return new ATSReturnStatement(value);}
    throw new Error("Missing return statement in function");
  }

  final public ATSValueReference value(ATSLocalVarsHelper localVars) throws ParseException {
        ATSValueReference reference;
        ATSPrimitiveOperation operation = null;
        Token tok;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MAP:
    case WORLD:
    case ATTACK:
    case PLAYER:
    case ACTOR:
    case ITEM:
    case BOOL:
    case NUM:
    case STRING:
    case OBJECT:
    case IDENTIFIER:
      reference = reference(localVars);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case GOE:
      case LOE:
      case GT:
      case LT:
      case EQ:
      case PLUS:
      case MINUS:
      case MULTIPLY:
      case DIVIDE:
      case CONCAT:
      case AND:
      case OR:
        operation = valueOp(localVars, reference);
        break;
      default:
        jj_la1[13] = jj_gen;
        ;
      }
                if (operation != null) {
                        {if (true) return operation;}
                } else {
                        {if (true) return reference;}
                }
      break;
    case NUMBER:
      tok = jj_consume_token(NUMBER);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case GOE:
      case LOE:
      case GT:
      case LT:
      case EQ:
      case PLUS:
      case MINUS:
      case MULTIPLY:
      case DIVIDE:
      case CONCAT:
      case AND:
      case OR:
        operation = valueOp(localVars, new ATSConstantReference(new Double(tok.image)));
        break;
      default:
        jj_la1[14] = jj_gen;
        ;
      }
                if (operation != null) {
                        {if (true) return operation;}
                } else {
                        {if (true) return new ATSConstantReference(new Double(tok.image));}
                }
      break;
    case LPAR:
      jj_consume_token(LPAR);
      reference = value(localVars);
      jj_consume_token(RPAR);
                {if (true) return reference;}
      break;
    case EXCLAM:
      jj_consume_token(EXCLAM);
      reference = value(localVars);
                {if (true) return new ATSPrimitiveOperation(ATSPrimitiveOperation.Operator.not, null, reference);}
      break;
    case TRUE:
      jj_consume_token(TRUE);
                {if (true) return new ATSConstantReference(Boolean.TRUE);}
      break;
    case FALSE:
      jj_consume_token(FALSE);
                {if (true) return new ATSConstantReference(Boolean.FALSE);}
      break;
    case DQUO:
      jj_consume_token(DQUO);
      tok = jj_consume_token(LITERAL_VALUE);
      jj_consume_token(DQUOBIS);
                {if (true) return new ATSConstantReference(tok.image);}
      break;
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ATSPrimitiveOperation valueOp(ATSLocalVarsHelper localVars, ATSValueReference leftHand) throws ParseException {
        ATSValueReference value;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case GT:
      jj_consume_token(GT);
      value = value(localVars);
                {if (true) return new ATSPrimitiveOperation(ATSPrimitiveOperation.Operator.gt, leftHand, value);}
      break;
    case LT:
      jj_consume_token(LT);
      value = value(localVars);
                {if (true) return new ATSPrimitiveOperation(ATSPrimitiveOperation.Operator.lt, leftHand, value);}
      break;
    case GOE:
      jj_consume_token(GOE);
      value = value(localVars);
                {if (true) return new ATSPrimitiveOperation(ATSPrimitiveOperation.Operator.goe, leftHand, value);}
      break;
    case LOE:
      jj_consume_token(LOE);
      value = value(localVars);
                {if (true) return new ATSPrimitiveOperation(ATSPrimitiveOperation.Operator.loe, leftHand, value);}
      break;
    case EQ:
      jj_consume_token(EQ);
      value = value(localVars);
                {if (true) return new ATSPrimitiveOperation(ATSPrimitiveOperation.Operator.eq, leftHand, value);}
      break;
    case PLUS:
      jj_consume_token(PLUS);
      value = value(localVars);
                {if (true) return new ATSPrimitiveOperation(ATSPrimitiveOperation.Operator.plus, leftHand, value);}
      break;
    case MINUS:
      jj_consume_token(MINUS);
      value = value(localVars);
                {if (true) return new ATSPrimitiveOperation(ATSPrimitiveOperation.Operator.minus, leftHand, value);}
      break;
    case MULTIPLY:
      jj_consume_token(MULTIPLY);
      value = value(localVars);
                {if (true) return new ATSPrimitiveOperation(ATSPrimitiveOperation.Operator.multiply, leftHand, value);}
      break;
    case DIVIDE:
      jj_consume_token(DIVIDE);
      value = value(localVars);
                {if (true) return new ATSPrimitiveOperation(ATSPrimitiveOperation.Operator.divide, leftHand, value);}
      break;
    case CONCAT:
      jj_consume_token(CONCAT);
      value = value(localVars);
                {if (true) return new ATSPrimitiveOperation(ATSPrimitiveOperation.Operator.concat, leftHand, value);}
      break;
    case AND:
      jj_consume_token(AND);
      value = value(localVars);
                {if (true) return new ATSPrimitiveOperation(ATSPrimitiveOperation.Operator.and, leftHand, value);}
      break;
    case OR:
      jj_consume_token(OR);
      value = value(localVars);
                {if (true) return new ATSPrimitiveOperation(ATSPrimitiveOperation.Operator.or, leftHand, value);}
      break;
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ATSValueReference mapReference(ATSLocalVarsHelper localVars, ATSValueReference targetInstance) throws ParseException {
        ATSValueReference param1;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OUTDOOR:
      jj_consume_token(OUTDOOR);
                {if (true) return new ATSObjectFieldReference(ATSObjectFieldReference.ObjectFields.mapOutdoor, targetInstance);}
      break;
    case ACTIVATEGROUP:
      jj_consume_token(ACTIVATEGROUP);
      jj_consume_token(LPAR);
      param1 = value(localVars);
      jj_consume_token(RPAR);
                {if (true) return new ATSMethodCall(ATSMethodCall.ObjectMethod.mapActivateGroup, new ATSValueReference[]{param1}, targetInstance);}
      break;
    case DEACTIVATEGROUP:
      jj_consume_token(DEACTIVATEGROUP);
      jj_consume_token(LPAR);
      param1 = value(localVars);
      jj_consume_token(RPAR);
                {if (true) return new ATSMethodCall(ATSMethodCall.ObjectMethod.mapDeactivateGroup, new ATSValueReference[]{param1}, targetInstance);}
      break;
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ATSValueReference attackReference(ATSLocalVarsHelper localVars) throws ParseException {
                {if (true) return null;}
    throw new Error("Missing return statement in function");
  }

  final public ATSValueReference playerReference(ATSLocalVarsHelper localVars) throws ParseException {
        ATSValueReference ref;
        ATSValueReference param1, param2;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ADDCONDITION:
    case CLEARCONDITION:
    case HP:
    case AP:
    case AC:
    case AD:
    case BC:
      ref = actorReference(localVars, new ATSContextObjectReference(ATSContextObjectReference.ContextObject.player));
                {if (true) return ref;}
      break;
    case BASE:
      jj_consume_token(BASE);
      jj_consume_token(DOT);
      ref = playerBaseReference(localVars, new ATSContextObjectReference(ATSContextObjectReference.ContextObject.player));
                {if (true) return ref;}
      break;
    case GETITEMCOUNT:
      jj_consume_token(GETITEMCOUNT);
      jj_consume_token(LPAR);
      param1 = value(localVars);
      jj_consume_token(RPAR);
                {if (true) return new ATSMethodCall(ATSMethodCall.ObjectMethod.getItemCount, new ATSValueReference[]{param1}, new ATSContextObjectReference(ATSContextObjectReference.ContextObject.player));}
      break;
    case GIVEITEM:
      jj_consume_token(GIVEITEM);
      jj_consume_token(LPAR);
      param1 = value(localVars);
      jj_consume_token(COMA);
      param2 = value(localVars);
      jj_consume_token(RPAR);
                {if (true) return new ATSMethodCall(ATSMethodCall.ObjectMethod.giveItem, new ATSValueReference[]{param1, param2}, new ATSContextObjectReference(ATSContextObjectReference.ContextObject.player));}
      break;
    case REMOVEITEM:
      jj_consume_token(REMOVEITEM);
      jj_consume_token(LPAR);
      param1 = value(localVars);
      jj_consume_token(COMA);
      param2 = value(localVars);
      jj_consume_token(RPAR);
                {if (true) return new ATSMethodCall(ATSMethodCall.ObjectMethod.removeItem, new ATSValueReference[]{param1, param2}, new ATSContextObjectReference(ATSContextObjectReference.ContextObject.player));}
      break;
    case GETITEMINSLOT:
      jj_consume_token(GETITEMINSLOT);
      jj_consume_token(LPAR);
      param1 = value(localVars);
      jj_consume_token(RPAR);
                {if (true) return new ATSMethodCall(ATSMethodCall.ObjectMethod.getItemInSlot, new ATSValueReference[]{param1}, new ATSContextObjectReference(ATSContextObjectReference.ContextObject.player));}
      break;
    case EQUIPITEMINSLOT:
      jj_consume_token(EQUIPITEMINSLOT);
      jj_consume_token(LPAR);
      param1 = value(localVars);
      jj_consume_token(COMA);
      param2 = value(localVars);
      jj_consume_token(RPAR);
                {if (true) return new ATSMethodCall(ATSMethodCall.ObjectMethod.equipItemInSlot, new ATSValueReference[]{param1, param2}, new ATSContextObjectReference(ATSContextObjectReference.ContextObject.player));}
      break;
    case UNEQUIPSLOT:
      jj_consume_token(UNEQUIPSLOT);
      jj_consume_token(LPAR);
      param1 = value(localVars);
      jj_consume_token(RPAR);
                {if (true) return new ATSMethodCall(ATSMethodCall.ObjectMethod.unequipSlot, new ATSValueReference[]{param1}, new ATSContextObjectReference(ATSContextObjectReference.ContextObject.player));}
      break;
    case HASQUESTPROGRESS:
      jj_consume_token(HASQUESTPROGRESS);
      jj_consume_token(LPAR);
      param1 = value(localVars);
      jj_consume_token(COMA);
      param2 = value(localVars);
      jj_consume_token(RPAR);
                {if (true) return new ATSMethodCall(ATSMethodCall.ObjectMethod.hasQuestProgress, new ATSValueReference[]{param1, param2}, new ATSContextObjectReference(ATSContextObjectReference.ContextObject.player));}
      break;
    case ADDQUESTPROGRESS:
      jj_consume_token(ADDQUESTPROGRESS);
      jj_consume_token(LPAR);
      param1 = value(localVars);
      jj_consume_token(COMA);
      param2 = value(localVars);
      jj_consume_token(RPAR);
                {if (true) return new ATSMethodCall(ATSMethodCall.ObjectMethod.addQuestProgress, new ATSValueReference[]{param1, param2}, new ATSContextObjectReference(ATSContextObjectReference.ContextObject.player));}
      break;
    case ADDEXPERIENCE:
      jj_consume_token(ADDEXPERIENCE);
      jj_consume_token(LPAR);
      param1 = value(localVars);
      jj_consume_token(RPAR);
                {if (true) return new ATSMethodCall(ATSMethodCall.ObjectMethod.addExperience, new ATSValueReference[]{param1}, new ATSContextObjectReference(ATSContextObjectReference.ContextObject.player));}
      break;
    case ADDALIGNMENT:
      jj_consume_token(ADDALIGNMENT);
      jj_consume_token(LPAR);
      param1 = value(localVars);
      jj_consume_token(COMA);
      param2 = value(localVars);
      jj_consume_token(RPAR);
                {if (true) return new ATSMethodCall(ATSMethodCall.ObjectMethod.addAlignment, new ATSValueReference[]{param1, param2}, new ATSContextObjectReference(ATSContextObjectReference.ContextObject.player));}
      break;
    case GETALIGNMENT:
      jj_consume_token(GETALIGNMENT);
      jj_consume_token(LPAR);
      param1 = value(localVars);
      jj_consume_token(RPAR);
                {if (true) return new ATSMethodCall(ATSMethodCall.ObjectMethod.addAlignment, new ATSValueReference[]{param1}, new ATSContextObjectReference(ATSContextObjectReference.ContextObject.player));}
      break;
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ATSValueReference playerBaseReference(ATSLocalVarsHelper localVars, ATSContextObjectReference targetInstance) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MAXHP:
      jj_consume_token(MAXHP);
                {if (true) return new ATSObjectFieldReference(ATSObjectFieldReference.ObjectFields.playerBaseMaxHP, targetInstance);}
      break;
    case MAXAP:
      jj_consume_token(MAXAP);
                {if (true) return new ATSObjectFieldReference(ATSObjectFieldReference.ObjectFields.playerBaseMaxAP, targetInstance);}
      break;
    case MOVECOST:
      jj_consume_token(MOVECOST);
                {if (true) return new ATSObjectFieldReference(ATSObjectFieldReference.ObjectFields.playerBaseMoveCost, targetInstance);}
      break;
    case EQUIPCOST:
      jj_consume_token(EQUIPCOST);
                {if (true) return new ATSObjectFieldReference(ATSObjectFieldReference.ObjectFields.playerBaseEquipCost, targetInstance);}
      break;
    case USECOST:
      jj_consume_token(USECOST);
                {if (true) return new ATSObjectFieldReference(ATSObjectFieldReference.ObjectFields.playerBaseUseCost, targetInstance);}
      break;
    case AC:
      jj_consume_token(AC);
                {if (true) return new ATSObjectFieldReference(ATSObjectFieldReference.ObjectFields.playerBaseAc, targetInstance);}
      break;
    case BC:
      jj_consume_token(BC);
                {if (true) return new ATSObjectFieldReference(ATSObjectFieldReference.ObjectFields.playerBaseBc, targetInstance);}
      break;
    default:
      jj_la1[19] = jj_gen;
      if (jj_2_1(3)) {
        jj_consume_token(AD);
        jj_consume_token(DOT);
        jj_consume_token(MIN);
                {if (true) return new ATSObjectFieldReference(ATSObjectFieldReference.ObjectFields.playerBaseAdMin, targetInstance);}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case AD:
          jj_consume_token(AD);
          jj_consume_token(DOT);
          jj_consume_token(MIN);
                {if (true) return new ATSObjectFieldReference(ATSObjectFieldReference.ObjectFields.playerBaseAdMax, targetInstance);}
          break;
        default:
          jj_la1[20] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public ATSValueReference actorReference(ATSLocalVarsHelper localVars, ATSContextObjectReference targetInstance) throws ParseException {
        ATSValueReference condId, condMagnitude, condDuration, condChance;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case AC:
      jj_consume_token(AC);
                {if (true) return new ATSObjectFieldReference(ATSObjectFieldReference.ObjectFields.actorAc, targetInstance);}
      break;
    case BC:
      jj_consume_token(BC);
                {if (true) return new ATSObjectFieldReference(ATSObjectFieldReference.ObjectFields.actorBc, targetInstance);}
      break;
    default:
      jj_la1[21] = jj_gen;
      if (jj_2_2(3)) {
        jj_consume_token(HP);
        jj_consume_token(DOT);
        jj_consume_token(CUR);
                {if (true) return new ATSObjectFieldReference(ATSObjectFieldReference.ObjectFields.actorHpCur, targetInstance);}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case HP:
          jj_consume_token(HP);
          jj_consume_token(DOT);
          jj_consume_token(MAX);
                {if (true) return new ATSObjectFieldReference(ATSObjectFieldReference.ObjectFields.actorHpMax, targetInstance);}
          break;
        default:
          jj_la1[22] = jj_gen;
          if (jj_2_3(3)) {
            jj_consume_token(AP);
            jj_consume_token(DOT);
            jj_consume_token(CUR);
                {if (true) return new ATSObjectFieldReference(ATSObjectFieldReference.ObjectFields.actorApCur, targetInstance);}
          } else {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case AP:
              jj_consume_token(AP);
              jj_consume_token(DOT);
              jj_consume_token(MAX);
                {if (true) return new ATSObjectFieldReference(ATSObjectFieldReference.ObjectFields.actorApMax, targetInstance);}
              break;
            default:
              jj_la1[23] = jj_gen;
              if (jj_2_4(3)) {
                jj_consume_token(AD);
                jj_consume_token(DOT);
                jj_consume_token(MIN);
                {if (true) return new ATSObjectFieldReference(ATSObjectFieldReference.ObjectFields.actorAdMin, targetInstance);}
              } else {
                switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
                case AD:
                  jj_consume_token(AD);
                  jj_consume_token(DOT);
                  jj_consume_token(MAX);
                {if (true) return new ATSObjectFieldReference(ATSObjectFieldReference.ObjectFields.actorAdMax, targetInstance);}
                  break;
                case ADDCONDITION:
                  jj_consume_token(ADDCONDITION);
                  jj_consume_token(LPAR);
                  condId = value(localVars);
                  jj_consume_token(COMA);
                  condMagnitude = value(localVars);
                  jj_consume_token(COMA);
                  condDuration = value(localVars);
                  jj_consume_token(COMA);
                  condChance = value(localVars);
                  jj_consume_token(RPAR);
                {if (true) return new ATSMethodCall(ATSMethodCall.ObjectMethod.actorAddCondition, new ATSValueReference[]{condId, condMagnitude, condDuration, condChance}, targetInstance);}
                  break;
                case CLEARCONDITION:
                  jj_consume_token(CLEARCONDITION);
                  jj_consume_token(LPAR);
                  condId = value(localVars);
                  jj_consume_token(COMA);
                  condChance = value(localVars);
                  jj_consume_token(RPAR);
                {if (true) return new ATSMethodCall(ATSMethodCall.ObjectMethod.actorClearCondition, new ATSValueReference[]{condId, condChance}, targetInstance);}
                  break;
                default:
                  jj_la1[24] = jj_gen;
                  jj_consume_token(-1);
                  throw new ParseException();
                }
              }
            }
          }
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public ATSValueReference worldReference(ATSLocalVarsHelper localVars) throws ParseException {
        ATSValueReference param1, objectCall = null;
    jj_consume_token(GETMAP);
    jj_consume_token(LPAR);
    param1 = value(localVars);
    jj_consume_token(RPAR);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DOT:
      jj_consume_token(DOT);
      objectCall = mapReference(localVars, new ATSMethodCall(ATSMethodCall.ObjectMethod.worldGetMap, new ATSValueReference[]{param1}, new ATSContextObjectReference(ATSContextObjectReference.ContextObject.world)));
      break;
    default:
      jj_la1[25] = jj_gen;
      ;
    }
                if (objectCall != null) {if (true) return objectCall;}
                {if (true) return new ATSMethodCall(ATSMethodCall.ObjectMethod.worldGetMap, new ATSValueReference[]{param1}, new ATSContextObjectReference(ATSContextObjectReference.ContextObject.world));}
    throw new Error("Missing return statement in function");
  }

  final public ATSValueReference itemReference(ATSLocalVarsHelper localVars, ATSContextObjectReference targetInstance) throws ParseException {
        ATSValueReference reference;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CATEGORY:
      jj_consume_token(CATEGORY);
                {if (true) return new ATSObjectFieldReference(ATSObjectFieldReference.ObjectFields.itemCategory, targetInstance);}
      break;
    case ID:
      jj_consume_token(ID);
                {if (true) return new ATSObjectFieldReference(ATSObjectFieldReference.ObjectFields.itemId, targetInstance);}
      break;
    case REWARD:
      jj_consume_token(REWARD);
      jj_consume_token(DOT);
      reference = itemRewardReference(localVars, targetInstance);
                {if (true) return reference;}
      break;
    default:
      jj_la1[26] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ATSValueReference itemRewardReference(ATSLocalVarsHelper localVars, ATSContextObjectReference targetInstance) throws ParseException {
    if (jj_2_5(3)) {
      jj_consume_token(HP);
      jj_consume_token(DOT);
      jj_consume_token(MAX);
                {if (true) return new ATSObjectFieldReference(ATSObjectFieldReference.ObjectFields.itemRewardHpMax, targetInstance);}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case HP:
        jj_consume_token(HP);
        jj_consume_token(DOT);
        jj_consume_token(MIN);
                {if (true) return new ATSObjectFieldReference(ATSObjectFieldReference.ObjectFields.itemRewardHpMin, targetInstance);}
        break;
      default:
        jj_la1[27] = jj_gen;
        if (jj_2_6(3)) {
          jj_consume_token(AP);
          jj_consume_token(DOT);
          jj_consume_token(MAX);
                {if (true) return new ATSObjectFieldReference(ATSObjectFieldReference.ObjectFields.itemRewardApMax, targetInstance);}
        } else {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case AP:
            jj_consume_token(AP);
            jj_consume_token(DOT);
            jj_consume_token(MIN);
                {if (true) return new ATSObjectFieldReference(ATSObjectFieldReference.ObjectFields.itemRewardApMin, targetInstance);}
            break;
          default:
            jj_la1[28] = jj_gen;
            if (jj_2_7(3)) {
              jj_consume_token(ACTORCONDITIONS);
              jj_consume_token(DOT);
              jj_consume_token(TOSOURCE);
                //TODO : implement Array support
                {if (true) return null;}
            } else {
              switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
              case ACTORCONDITIONS:
                jj_consume_token(ACTORCONDITIONS);
                jj_consume_token(DOT);
                jj_consume_token(TOTARGET);
                //TODO : implement Array support
                {if (true) return null;}
                break;
              default:
                jj_la1[29] = jj_gen;
                jj_consume_token(-1);
                throw new ParseException();
              }
            }
          }
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_3_5() {
    if (jj_scan_token(HP)) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(MAX)) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_scan_token(HP)) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(CUR)) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_scan_token(AD)) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(MIN)) return true;
    return false;
  }

  private boolean jj_3_6() {
    if (jj_scan_token(AP)) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(MAX)) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_scan_token(AP)) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(CUR)) return true;
    return false;
  }

  private boolean jj_3_7() {
    if (jj_scan_token(ACTORCONDITIONS)) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(TOSOURCE)) return true;
    return false;
  }

  private boolean jj_3_4() {
    if (jj_scan_token(AD)) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(MIN)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public ATScriptParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[30];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xd201,0xd000,0x80000000,0x0,0x0,0x20,0x20,0x20,0x20,0x20,0x0,0x2000,0x1100,0x7ff80000,0x7ff80000,0x70040,0x7ff80000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x20,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0xfc,0xfc,0x0,0xfc,0x0,0x0,0x0,0x0,0x0,0x0,0xfc,0x0,0x0,0x0,0x0,0xff,0x0,0x700,0x8ffc0000,0x0,0x0,0x0,0x0,0x0,0xc0000,0x0,0x30000,0x0,0x0,0x10000000,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0xf800000,0xf800000,0x0,0xf800000,0x7800000,0x0,0x0,0x0,0x0,0x0,0x8000000,0x0,0x0,0x0,0x0,0xf800000,0x0,0x0,0x1f620,0x1401f,0x8000,0x14000,0x1000,0x2000,0x8000,0x0,0x800,0x1000,0x2000,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[7];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public ATScriptParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public ATScriptParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ATScriptParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 30; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 30; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public ATScriptParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ATScriptParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 30; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 30; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public ATScriptParser(ATScriptParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 30; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(ATScriptParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 30; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[95];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 30; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 95; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 7; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
