/* Generated By:JavaCC: Do not edit this line. ATScriptInterpreterConstants.java */
package com.gpl.rpg.AndorsTrail.scripting.interpreter;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ATScriptInterpreterConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DOT = 5;
  /** RegularExpression Id. */
  int LPAR = 6;
  /** RegularExpression Id. */
  int RPAR = 7;
  /** RegularExpression Id. */
  int LBRAC = 8;
  /** RegularExpression Id. */
  int RBRAC = 9;
  /** RegularExpression Id. */
  int SCOL = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int ELSE = 12;
  /** RegularExpression Id. */
  int EXCLAM = 13;
  /** RegularExpression Id. */
  int GOE = 14;
  /** RegularExpression Id. */
  int LOE = 15;
  /** RegularExpression Id. */
  int GT = 16;
  /** RegularExpression Id. */
  int LT = 17;
  /** RegularExpression Id. */
  int EQ = 18;
  /** RegularExpression Id. */
  int PLUS = 19;
  /** RegularExpression Id. */
  int MINUS = 20;
  /** RegularExpression Id. */
  int MULTIPLY = 21;
  /** RegularExpression Id. */
  int DIVIDE = 22;
  /** RegularExpression Id. */
  int EQUALS = 23;
  /** RegularExpression Id. */
  int DQUO = 24;
  /** RegularExpression Id. */
  int NUMBER = 25;
  /** RegularExpression Id. */
  int MAP = 26;
  /** RegularExpression Id. */
  int WORLD = 27;
  /** RegularExpression Id. */
  int ATTACK = 28;
  /** RegularExpression Id. */
  int PLAYER = 29;
  /** RegularExpression Id. */
  int ACTOR = 30;
  /** RegularExpression Id. */
  int OUTDOOR = 31;
  /** RegularExpression Id. */
  int MIN = 32;
  /** RegularExpression Id. */
  int MAX = 33;
  /** RegularExpression Id. */
  int CURRENT = 34;
  /** RegularExpression Id. */
  int SOURCE = 35;
  /** RegularExpression Id. */
  int TARGET = 36;
  /** RegularExpression Id. */
  int DAMAGE = 37;
  /** RegularExpression Id. */
  int HP = 38;
  /** RegularExpression Id. */
  int AP = 39;
  /** RegularExpression Id. */
  int AC = 40;
  /** RegularExpression Id. */
  int AD = 41;
  /** RegularExpression Id. */
  int BC = 42;
  /** RegularExpression Id. */
  int DR = 43;
  /** RegularExpression Id. */
  int CC = 44;
  /** RegularExpression Id. */
  int CM = 45;
  /** RegularExpression Id. */
  int BOOL = 46;
  /** RegularExpression Id. */
  int NUM = 47;
  /** RegularExpression Id. */
  int IDENTIFIER = 48;
  /** RegularExpression Id. */
  int ESCAPED_DQUO = 49;
  /** RegularExpression Id. */
  int DQUOBIS = 50;
  /** RegularExpression Id. */
  int LITERAL_VALUE = 51;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int LITERAL = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"if\"",
    "\"else\"",
    "\"!\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"\\\"\"",
    "<NUMBER>",
    "\"map\"",
    "\"world\"",
    "\"attack\"",
    "\"player\"",
    "\"actor\"",
    "\"outdoor\"",
    "\"min\"",
    "\"max\"",
    "\"current\"",
    "\"source\"",
    "\"target\"",
    "\"damage\"",
    "\"hp\"",
    "\"ap\"",
    "\"ac\"",
    "\"ad\"",
    "\"bc\"",
    "\"dr\"",
    "\"cc\"",
    "\"cm\"",
    "\"bool\"",
    "\"num\"",
    "<IDENTIFIER>",
    "\"\\\\\\\"\"",
    "\"\\\"\"",
    "<LITERAL_VALUE>",
  };

}
